name: 'run-circleci-artifacts-redirector'
description: 'Check for CircleCI status update and maybe push our own'
author: 'Eric Larson'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
  artifact-path:
    description: 'Path to the CircleCI artifact'
    required: true
  circleci-jobs:
    description: 'Comma-separated list of CircleCI jobs to monitor (default is "build_docs,build,doc")'
    required: false
on: status
runs:
  using: 'node12'
  main: 'dist/index.js'
